version: "3.9"
services:
  api:
    build:
      context: ./backend
      dockerfile: ./backend/Dockerfile
      args:
        - target=dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    environment:
      ENV: dev
      PORT: 3000
